### ISSUE TITLE
 Error parsing dependencies

### ISSUE THREAD

**Issue by bep** [mitchellh/golicense#3]
https://github.com/gohugoio/hugo

```bash
▶ golicense ./hugo
❗️ Error parsing dependencies: Unexpected raw dependency format: dep	github.com/markbates/inflect	v1.0.0%
```

**Comment by mitchellh** [comment]
Thanks! This is fixed in https://github.com/mitchellh/golicense/commit/ac559e610f4714e5651cbb9ae7cbff331ae8fd40

Interesting bug, turns out the Go compiler puts a different syntax in the raw dep info for `replacement` directives. Releasing v0.1.1 now too.
